### ISSUE TITLE
Some users can't edit their site

### ISSUE THREAD

**Issue by nostrband** [nostrband/nostr-site-manager#100]
"Hey I tried editing something on my site, still getting the spinning circle"

Site https://the-orange-revolution.npub.pro/

Pubkey: npub18tgpyjxxdu79djz8ph8x8uzntga7w68n5z3fvuv7svy9r93d3grse30e7t

Need to check his relays, setup new npub with those relays, then try to create a website and see how well npub.pro works for such a profile.

**Comment by nostrband** [comment]
There was a server-side bug that probably caused this, I haven't seen other similar reports since then, so we should probably close this.

**Comment by leafes** [comment]
wasn't able to replicate, agree with closing the issue.
