### ISSUE TITLE
Hashtags editing doesn't work in settings

### ISSUE THREAD

**Issue by nostrband** [nostrband/nostr-site-manager#15]

**Comment by nostrband** [comment]
https://njump.me/nevent1qvzqqqqqqypzqp0yvjvr9hac6xl6s848e0cujtz0rn2s22lu342xtwn5f2n05h4cqy88wumn8ghj7mn0wvhxcmmv9uq3zamnwvaz7tmwdaehgu3wwa5kuef0qqsfa6uvfdy5x9vgxym8ncw0aqpkg42nutv0d6w9w89mj4ppksufzygcumrqr

**Comment by brugeman** [comment]
Fixed
