### ISSUE TITLE
Add zaps

### ISSUE THREAD

**Issue by nostrband** [nostrband/nostr-site-manager#26]
Zapper.fun? Not working w/o extension :(
Some zapper widget?
Custom zap implementation?

**Comment by nostrband** [comment]
Done

**Comment by LukeParker** [comment]
Is there a difference between Profile zaps and individual note/post zaps?

As an author I'd really like to see zaps per note prompted at the bottom of the page so I can track note/story performance.

**Comment by nostrband** [comment]
> Is there a difference between Profile zaps and individual note/post zaps?

Yes there is, note zaps have a link to specific note.

> As an author I'd really like to see zaps per note prompted at the bottom of the page so I can track note/story performance.

Most apps will show you the zap amount under each of your note.
