### ISSUE TITLE
Posting based on Hashtag in post

### ISSUE THREAD

**Issue by PlebOne** [nostrband/nostr-site-manager#44]
I've played around with posting via hashtag. It seems if I set a tag such as #blog and add it to the bottom of my post it will show up on my Npub.pro site. But if I have multiple tags such as #blog #nostr #etc ... at the bottom it does not pick up #blog and show it on the site. I  hoping to be able to filter this way as to not post every stupid thing I say to my npub.pro site.

**Comment by brugeman** [comment]
Hi, hashtags must be properly marked in your events using 't' tag (['t', '<hashtag>']), that's how we're able to fetch them from relays. Your long form posts with #blog and other hashtags in content doesn't mention these tags using 't' event tag. That's probably because the client you've used (Yakihonne?) doesn't support that. Try editing your post with Habla to see if that one adds hashtags properly.

**Comment by LukeParker** [comment]
I feel like this needs a lot more explaining. I don't know of any events field in any client like Primal or Iris, in which I can place a ['t', "] tag. Does Habla News have a feild like that? 

Nor do I know exactly how to use that tag. (Like would multiple tags be written as: 
`['t', 'term1' 'term2' 'term3']` ?) 

And when you put such code at the end of your note, won't other people see it & wonder why it's so junky looking?

**Comment by nostrband** [comment]
> I feel like this needs a lot more explaining.

Apps that support hashtags properly will parse the content you typed, find the #hashtags and put them into proper places inside the nostr event. Some apps don't do that yet, but that's a bug in those apps.

You don't need to do anything manually, just use a client with full support for hashtags. You can open your note in njump.me and open "detailed" view and check if your event has proper "t" tags added to it (one for each hashtag from your content).

**Comment by LukeParker** [comment]
Thanks for responding so quickly. 

Just so I didn't miss anything, the process I should take to post content on my NpubPro site is:

1. Place a hashtag like #SciFi in my NPubPro General settings page under "Content filters."
2. Write a note in a long-form-accepting client like Habla.news.
3. Finish the note with hashtags, simply placed there by a # sign like: #SciFi - No other code needed.
    (And ensure that the matching hashtag is the first one used so it indexes easily)
4. Publish the note, and it automagically appears on my NpubPro site. (Assuming I used the same npub for note and site.)

Did I miss anything?

**Comment by nostrband** [comment]
That's correct, although you don't have to place hashtags at the end of your note, and order doesn't matter. Just use #scifi anywhere in content (in lowercase preferably, there are several issues with upper-case hashtags across apps so it's might cause issues). If it's not working, please report a note id here so I could investigate.
