### ISSUE TITLE
Site admin page not available after site is published

### ISSUE THREAD

**Issue by nostrband** [nostrband/nostr-site-manager#46]
We need to put the new site to local site cache, otherwise it's not visible when we visit the admin page for the first time - need to reload the page first.

**Comment by LukeParker** [comment]
I'm having this problem too. All that was left on my home page (lukeparker.npub.pro) when I visited at first was the "home" link at the top and the login leaf to the right, Although it doesn't add any additional menus when I login. So I effectively had no way to add content or edit anything anymore.

I went searching through my browser history and came across the URL for the config page, which looks like:
'https://npub.pro/admin/naddr...veryLongStringHere.../dashboard'

Thankfully, when I go to that page again I can edit the site. There really should be some kind of link to it when logged in.

**Comment by nostrband** [comment]
Fixed
