### ISSUE TITLE
Formatting could use a major facelift

### ISSUE THREAD

**Issue by LukeParker** [nostrband/nostr-site-manager#60]
I used markup commands properly but it's still pretty hard to read my screenplay published here:
https://lukeparker.npub.pro/post/1725465332144/ 

In contrast, look at the exact same posting in Coracle: 
https://coracle.social/naddr1qqxnzdejx56rvdfnxverzdp5qyw8wumn8ghj7mn0wd68ytnzd96xxmmfdejhytnnda3kjctvqgs9w24gss2vdv2yxzp0umt2wzc2tgfjx40zva7xwglj5qsqufn226grqsqqqa28cxmhu7 

Or Habla.news:
https://habla.news/u/Luke@BitcoinNostr.com/1725465332144

I think the major thing they do better is the ample spacing. But your display also has the problem of making everything seem bolded, which makes it, in my case, impossible to see who said what. 

Some better image logic would be very useful, too.

Thanks in advance!

**Comment by nostrband** [comment]
The theme you've selected determines the styles of the posts. This particular theme uses no spacing between paragraphs and a bold font for content.

You could either choose a different theme, or customize it using code injections. Please paste the code below to the "Code inject in header" field in site settings:

```
<style>
p {
  font-weight: 400;
  margin: 1rem 0;
}
</style>
```

What do you mean by "better image logic"?

**Comment by LukeParker** [comment]
That header injection fixed the bolding issue, thank you. I'd like a little more spacing between paragraphs, however. 

By image logic I mean that it just pastes the picture uploaded for the top of the post without resizing in any way. Perhaps some kind of maximum height can be used and the picture displayed scaled down?

And that is for the post itself... On the website cover image it does scale to your screen's width, like it should, but my picture is far taller than I would have allowed a banner image. Basically my whole monitor shows the cover image and nothing below it. Cutting off the bottom to a max height & giving the author a maximum dimensions for the banner would be very nice there.

**Comment by nostrband** [comment]
>   margin: 1rem 0;

To increase margin btw paragraphs, increase the margin value from 1rem to 2rem etc in the code injection.

>By image logic I mean that it just pastes the picture uploaded for the top of the post without resizing in any way

That is theme's logic too. You could limit the max height using this code (adjust max-height value as needed), append it to header code injection:
```
<style>
.gh-article-image img {
    max-height: 500px;
    object-fit: contain;
}
</style>
```

I suggest we proceed this discussion on nostr, this isn't an issue with the engine or site-manager app. Theme customizations don't belong to github issues.
