### ISSUE TITLE
Multiple domains point to same siteId

### ISSUE THREAD

**Issue by nostrband** [nostrband/nostr-site-manager#86]
Many people manage to create several sites with same siteId, probably relates with them returning to /design?theme=X&siteId=Y but somehow it's not the original site that's edited by a new one is created.

**Comment by nostrband** [comment]
Looks like the issue was on the server with getSiteDomain returning deleted sites! Check that it's gone now.

**Comment by leafes** [comment]
@nostrband i'll take a look on this and will try to replicate

**Comment by nostrband** [comment]
There was a server-side bug that caused this, I haven't seen any more reports like this, so we should probably close it.

**Comment by leafes** [comment]
wasnt able to replicate, i agree with a closure of the issue
