### ISSUE TITLE
Add migration from delegated to "owned" mode

### ISSUE THREAD

**Issue by nostrband** [nostrband/nostr-site-manager#94]
In dashboard in delegated mode show big red "Migrate to own your site" button:
- shows a modal with explanation that "sign up with OTP makes your site signed by our own keys, you need to migrate to use your own keys to fully own your site". Next we should explain how to use nsec.app to store your keys and login (screenshots?), url /admin/siteId/own
- then user clicks "continue" we go to /admin/siteId/own/ready and show "Please log in with your keys" text and show nostr-login modal with "log in" screen, after user relogins the screen auto-reloads and the text on this page changes to "Migrate your site XXX to your own keys", and "Migrate" button
- click on "Migrate" does:
 - copy site event, change pubkey to user's, sign, publish
 - call /migrate?from=oldSiteId&to=newSiteId with "to" site id of newly signed event - it will re-render the new site to the same cdn directory
 - call DELETE /site?site=oldSiteId to make server delete the old site event
 - when all done we show "Success" text and "Back to dashboard" button which should open /admin/newSiteId/dashboard page
 
/migrate is TBD in nostr-site-cli

**Comment by nostrband** [comment]
Should be fixed by https://github.com/nostrband/nostr-site-manager/pull/127

**Comment by leafes** [comment]
tested on [feature/otp-migrate](https://github.com/nostrband/nostr-site-manager/tree/feature/otp-migrate). Fixed.
