### ISSUE TITLE
Disable "Edit" button in general settings and theme edit sidebar and display alert for readonly profiles

### ISSUE THREAD

**Issue by leafes** [nostrband/nostr-site-manager#96]
User isn't able to edit these fields in read-only mode. 

I suggest to disable them and show alert that notify user about inability to edit those fields.

pages:
/design (edit and new website)
/admin/xxx/settings (edit)

**Comment by leafes** [comment]
tested, tooltip showed for read-only users ![Image](https://github.com/user-attachments/assets/28a76fb5-f1af-4e45-8677-8bfdcba30e26)

**Comment by nostrband** [comment]
@leafes please log a new issue - if site is created under OTP but user is now logged in with Connect OR vice-versa (created under connect but site is OTP) then same icon must be shown with a different text. I will implement it later.
